#!/usr/bin/env python3
"""
Self-Healing Architecture Auditor for BillyRonks Global
Validates the existence of critical Blueprint files and auto-creates GitHub issues for gaps.
"""

import os
import sys
from pathlib import Path
from github import Github


# Critical files defined in the BillyRonks Blueprint
CRITICAL_FILES = [
    'CLAUDE.md',
    '.github/CODEOWNERS',
    '.github/workflows/market_scan.yml',
    '.coderabbit.yaml'
]

# Critical directories that must not be empty
CRITICAL_DIRS = {
    'docs/architecture/': 'must contain architecture documentation'
}


def check_file_exists(file_path):
    """
    Check if a file exists in the repository.

    Args:
        file_path: Relative path to the file

    Returns:
        True if file exists, False otherwise
    """
    base_path = Path(__file__).parent.parent
    full_path = base_path / file_path
    return full_path.exists() and full_path.is_file()


def check_dir_empty(dir_path):
    """
    Check if a directory is empty (ignoring .gitkeep files).

    Args:
        dir_path: Relative path to the directory

    Returns:
        True if empty (or only contains .gitkeep), False otherwise
    """
    base_path = Path(__file__).parent.parent
    full_path = base_path / dir_path

    if not full_path.exists() or not full_path.is_dir():
        return True  # Treat non-existent dir as empty

    # Check for files other than .gitkeep
    files = [f for f in full_path.iterdir() if f.name != '.gitkeep']
    return len(files) == 0


def search_existing_issue(github_client, repo_name, filename):
    """
    Search for existing open issues about the missing file.

    Args:
        github_client: GitHub client instance
        repo_name: Repository name (owner/repo)
        filename: Name of the missing file

    Returns:
        True if an open issue exists, False otherwise
    """
    try:
        repo = github_client.get_repo(repo_name)

        # Search for open issues with "Critical Gap" in title and the filename
        issues = repo.get_issues(state='open', labels=['maintenance'])

        for issue in issues:
            if f'Critical Gap: Missing {filename}' in issue.title:
                print(f"   ⊘ Issue already exists for {filename}: #{issue.number}")
                return True

        return False

    except Exception as e:
        print(f"   ✗ Error searching issues: {e}")
        return False


def create_gap_issue(github_client, repo_name, filename):
    """
    Create a GitHub issue for a missing critical file.

    Args:
        github_client: GitHub client instance
        repo_name: Repository name (owner/repo)
        filename: Name of the missing file

    Returns:
        Created issue object or None
    """
    try:
        repo = github_client.get_repo(repo_name)

        # Get or create the maintenance label
        try:
            label = repo.get_label('maintenance')
        except:
            label = repo.create_label('maintenance', 'FFA500', 'Repository maintenance and infrastructure')

        title = f"Critical Gap: Missing {filename}"
        body = f"""The Autonomous Auditor detected that `{filename}` is missing. This violates the BillyRonks Blueprint. Please restore it.

---
*Auto-generated by Architecture Audit System*"""

        issue = repo.create_issue(
            title=title,
            body=body,
            labels=[label]
        )

        print(f"   ✓ Created issue #{issue.number}: Missing {filename}")
        return issue

    except Exception as e:
        print(f"   ✗ Error creating issue: {e}")
        return None


def main():
    """Main execution function."""
    print("🔍 BillyRonks Architecture Auditor")
    print("=" * 50)

    # Check for GitHub token
    github_token = os.getenv('GITHUB_TOKEN')
    github_repo = os.getenv('GITHUB_REPOSITORY')

    if not github_token:
        print("\n❌ Error: GITHUB_TOKEN environment variable not set")
        return 1

    if not github_repo:
        print("\n⚠️  Warning: GITHUB_REPOSITORY not set, using default 'billyronks/billyronks-production-01'")
        github_repo = 'billyronks/billyronks-production-01'

    github_client = Github(github_token)

    # Track audit results
    missing_files = []
    empty_dirs = []
    issues_created = 0
    issues_existing = 0

    # Step 1: Check critical files
    print("\n📋 Step 1: Auditing critical files...")
    for file_path in CRITICAL_FILES:
        print(f"   Checking {file_path}...", end=' ')

        if check_file_exists(file_path):
            print("✓")
        else:
            print("✗ MISSING")
            missing_files.append(file_path)

    # Step 2: Check critical directories
    print("\n📁 Step 2: Auditing critical directories...")
    for dir_path, description in CRITICAL_DIRS.items():
        print(f"   Checking {dir_path}...", end=' ')

        if check_dir_empty(dir_path):
            print(f"✗ EMPTY ({description})")
            empty_dirs.append(dir_path)
        else:
            print("✓")

    # Step 3: Create issues for gaps
    if missing_files or empty_dirs:
        print("\n🔧 Step 3: Processing detected gaps...")

        for file_path in missing_files:
            print(f"\n   Processing missing file: {file_path}")

            # Check if issue already exists
            if search_existing_issue(github_client, github_repo, file_path):
                issues_existing += 1
                continue

            # Create new issue
            issue = create_gap_issue(github_client, github_repo, file_path)
            if issue:
                issues_created += 1

        for dir_path in empty_dirs:
            print(f"\n   Processing empty directory: {dir_path}")

            # Check if issue already exists
            if search_existing_issue(github_client, github_repo, dir_path):
                issues_existing += 1
                continue

            # Create new issue
            issue = create_gap_issue(github_client, github_repo, dir_path)
            if issue:
                issues_created += 1
    else:
        print("\n✅ All critical files and directories are in place!")

    # Summary
    print("\n" + "=" * 50)
    print("✅ Audit complete!")
    print(f"   Critical files checked: {len(CRITICAL_FILES)}")
    print(f"   Critical directories checked: {len(CRITICAL_DIRS)}")
    print(f"   Missing files: {len(missing_files)}")
    print(f"   Empty directories: {len(empty_dirs)}")
    print(f"   New issues created: {issues_created}")
    print(f"   Existing issues found: {issues_existing}")

    # Return non-zero exit code if gaps were found
    if missing_files or empty_dirs:
        return 1

    return 0


if __name__ == '__main__':
    try:
        exit(main())
    except KeyboardInterrupt:
        print("\n\n⚠️  Audit interrupted by user")
        exit(130)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        exit(1)